# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-11.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-11.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/evansjr/src/ctools/dirsort

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/evansjr/src/ctools/dirsort

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-11.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-11.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/evansjr/src/ctools/dirsort/CMakeFiles /Users/evansjr/src/ctools/dirsort/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/evansjr/src/ctools/dirsort/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TDocument

# Build rule for target.
TDocument: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TDocument
.PHONY : TDocument

# fast build rule for target.
TDocument/fast:
	$(MAKE) -f CMakeFiles/TDocument.dir/build.make CMakeFiles/TDocument.dir/build
.PHONY : TDocument/fast

#=============================================================================
# Target rules for targets named dirsort

# Build rule for target.
dirsort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dirsort
.PHONY : dirsort

# fast build rule for target.
dirsort/fast:
	$(MAKE) -f CMakeFiles/dirsort.dir/build.make CMakeFiles/dirsort.dir/build
.PHONY : dirsort/fast

dirsort.o: dirsort.c.o
.PHONY : dirsort.o

# target to build an object file
dirsort.c.o:
	$(MAKE) -f CMakeFiles/dirsort.dir/build.make CMakeFiles/dirsort.dir/dirsort.c.o
.PHONY : dirsort.c.o

dirsort.i: dirsort.c.i
.PHONY : dirsort.i

# target to preprocess a source file
dirsort.c.i:
	$(MAKE) -f CMakeFiles/dirsort.dir/build.make CMakeFiles/dirsort.dir/dirsort.c.i
.PHONY : dirsort.c.i

dirsort.s: dirsort.c.s
.PHONY : dirsort.s

# target to generate assembly for a file
dirsort.c.s:
	$(MAKE) -f CMakeFiles/dirsort.dir/build.make CMakeFiles/dirsort.dir/dirsort.c.s
.PHONY : dirsort.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... TDocument"
	@echo "... dirsort"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dirsort.o"
	@echo "... dirsort.i"
	@echo "... dirsort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

